<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>ЦМСКА - <?=isset($title) ? $title : "главная"?> - Быстрейшая!</title>
		<meta name="Keywords" content="<?=isset($keywords) ? $keywords : $this->utils->get_text("index_keywords");?>">
		<meta name="Description" content="<?=isset($description) ? $description : $this->utils->get_text("index_description");?>">
		<meta name="robots" content="all"/>
		<script type="text/javascript" src="http://pricel24.ru/js/jquery.js"></script>
		<script type="text/javascript" src="/js/script.js"></script>
		<script type="text/javascript" src="/js/jquery.range-min.js"></script>
		
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="css/ie.css">
		<![endif]-->
		<link rel="stylesheet" type="text/css" href="/css/jquery.range.css">
	</head>
	<body>
	</body>
</html>
